version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  go-server:
    build: .
    container_name: go_server
    ports:
      - "8080:8080" # Expose port 8080 for the Go server
    environment:
      DATABASE_URL: postgres://myuser:mypassword@postgres:5432/mydatabase?sslmode=disable
    depends_on:
      - postgres

volumes:
  postgres_data:
